### ISSUE TITLE
Bug avec EquationDiophantienne

### ISSUE THREAD

**Issue by fabricelallemand15** [cpierquet/ProfLycee#2]
Bonjour,

Tout d'abord, un grand merci pour votre travail en ce qui concerne le paquet LaTeX ProfLycee que je suis en train de découvrir.

J'ai une fonction qui provoque une erreur :
\EquationDiophantienne{3x+4y=1}

L'erreur est  : 
Extra alignment tab has been changed to \cr.

Même sans aucun autre paquet autour de ProfLycee, l'erreur persiste.
Bien cordialement,
-- 
Fabrice LALLEMAND

**Comment by cpierquet** [comment]
Bonjour, je n'arrive pas à reproduire le dysfonctionnement, cela fonctionne chez moi et sur un compilateur en ligne... (avez-vous le fichier log créé ?)

Vos packages sont-ils bien mis à jour ?

![image](https://github.com/cpierquet/ProfLycee/assets/45103962/f8d1bd93-8934-426f-8f35-bf3502b4ac34)
