### ISSUE TITLE
graduation d'axe

### ISSUE THREAD

**Issue by mbriffoteaux** [cpierquet/ProfLycee#3]
Bonjour,
avec le code suivant
`xmin=0,xmax=0.3,xgrille=0.05,xgrilles=.005, %axe Ox
ymin=0,ymax=2.5,ygrille=1,ygrilles=.1] %axe Oy
\FenetreSimpleTikz%
<Police=\scriptsize>{0,0.05,...,.3}%
<Police=\scriptsize>{0,.5,...,2.5} %repère
%\CourbeTikz[line width=1.25pt,CouleurVertForet,samples=250]%
%{9*exp(-0.12*\x)+10}{0:10} %courbe
\end{tikzpicture}`

j'obtiens la graduation suivante (voir pj)

me voilà bloqué :)
bien cordialement,
![bug](https://github.com/cpierquet/ProfLycee/assets/160837992/017e49c5-9d69-42fe-8b71-9a2a55761d8b)

**Comment by cpierquet** [comment]
C'est un souci classique avec les décimaux... Dans ce cas on peut s'en sortir en mettant toutes les valeurs dans la déclaration des graduations : `{0,0.05,0.1,0.15,0.2,0.25,0.3}`
![2024-02-22-10-04-05 msedge IU4R](https://github.com/cpierquet/ProfLycee/assets/45103962/628c2127-ec24-49e0-88eb-16dbbe16c518)
