### ISSUE TITLE
beamer et ProfLycee

### ISSUE THREAD

**Issue by mbriffoteaux** [cpierquet/ProfLycee#4]
Bonjour,
j''ai tenté :

\begin{frame}

\begin{tikzpicture}[x=1.5cm,y=0.0167cm, %unités
xmin=0,xmax=6,xgrille=1,xgrilles=.5, %axe Ox
ymin=0,ymax=700,ygrille=100,ygrilles=50] %axe Oy
\FenetreSimpleTikz%
<Police=\small>{auto}%
<Police=\small>{auto} %repère
\CourbeTikz[line width=1.25pt,blue,samples=250]%
{106*\x}{0:6} %courbe1
\CourbeTikz[line width=1.25pt,red,samples=250]%
{-5.5*\x*\x*\x+49*\x*\x+10*\x}{0:6} %courbe1
\end{tikzpicture}

\end{frame}

et ça me renvoie : 

! Package listofitems Error: 2 is an invalid index, index [] retained.
See the listofitems package documentation for explanation.
Type H <return> for immediate help.

je ne sais pas si c'est bien posté... je ne suis pas vraiment habitué à Github.

ps : le code ProfLycee passe dans un documentclass{article}

**Comment by cpierquet** [comment]
Bonjour, le code compile normalement sur le compilateur en ligne, les packages sont-ils bien tous à jour ?

![image](https://github.com/cpierquet/ProfLycee/assets/45103962/a564e51f-dc81-4c63-8690-254148843635)

**Comment by mbriffoteaux** [comment]
Bonjour,
merci d'avoir répondu :)
j'ai fait un ECM 
``
\documentclass[10pt]{beamer}
%\usetheme{Warsaw}
\usetheme{Boadilla}
\usepackage{ProfLycee}
\usepackage{ProfCollege}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
%\subject{} 
\title{Résolution graphique d'équations / inéquations}
\begin{document}
\maketitle




\begin{frame}

\begin{tikzpicture}[x=1.5cm,y=0.0167cm, %unités
xmin=0,xmax=6,xgrille=1,xgrilles=.5, %axe Ox
ymin=0,ymax=700,ygrille=100,ygrilles=50] %axe Oy
\FenetreSimpleTikz%
<Police=\small>{auto}%
<Police=\small>{auto} %repère
\CourbeTikz[line width=1.25pt,blue,samples=250]%
{106*\x}{0:6} %courbe1
\CourbeTikz[line width=1.25pt,red,samples=250]%
{-5.5*\x*\x*\x+49*\x*\x+10*\x}{0:6} %courbe1
\end{tikzpicture}

\end{frame}
\end{document}``

même erreur mais au moins j'ai viré tout ce que j'ai pu.

cordialement,

**Comment by cpierquet** [comment]
Il semble (après je n'ai pas poussé mes recherches) qu'en déclarant les `frame` avec `[fragile]` cela fonctionne, je pense que ça droit être lié à des _codes_ ou _environnements_ proposés par ProfLycee et/ou ProfCollege...

```
\documentclass[10pt]{beamer}
\usetheme{Boadilla}
\usepackage{ProfLycee}
\usepackage{ProfCollege}
\usepackage[utf8]{inputenc}
\usepackage[french]{babel}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
%\subject{}
\title{Résolution graphique d'équations / inéquations}
\begin{document}
\maketitle

\begin{frame}[fragile]

\begin{tikzpicture}[x=1.5cm,y=0.01cm, %unités
	xmin=0,xmax=6,xgrille=1,xgrilles=.5, %axe Ox
	ymin=0,ymax=700,ygrille=100,ygrilles=50] %axe Oy
	\FenetreSimpleTikz%
	<Police=\small>{auto}%
	<Police=\small>{auto} %repère
	\CourbeTikz[line width=1.25pt,blue,samples=250]%
	{106*\x}{0:6} %courbe1
	\CourbeTikz[line width=1.25pt,red,samples=250]%
	{-5.5*\x*\x*\x+49*\x*\x+10*\x}{0:6} %courbe1
\end{tikzpicture}

\end{frame}
\end{document}
```
![image](https://github.com/cpierquet/ProfLycee/assets/45103962/5e246af4-e56d-4319-8551-2824dc701760)

**Comment by mbriffoteaux** [comment]
ok merci :)
je mettrai tout bien à jour et testerai de temps en temps.
merci encore.
cordialement,
