### ISSUE TITLE
Version 3.04c : Disparition des commandes TerminalWin, TerminalUnix, TerminalOSX

### ISSUE THREAD

**Issue by obook** [cpierquet/ProfLycee#5]
Bonjour.
Y a t-il une commande de remplacement pour ces trois commandes qui ont disparues dans la V3.0.4 ?
Elle me servaient régulièrement pour NSI.
Merci.

**Comment by obook** [comment]
Finalement, je vais utiliser le paquet sim-os-menus : https://ctan.org/pkg/sim-os-menus
Merci.

**Comment by cpierquet** [comment]
Bonjour, effectivement les commandes ont disparu de `ProfLycee` car je les ai implémentées dans mon package `sim-os-menus` ;-)
