### ISSUE TITLE
Make some version of exercise from a list of three points 

### ISSUE THREAD

**Issue by minhthien2016** [cpierquet/ProfLycee#6]
I see [this question](https://mathematica.stackexchange.com/questions/304538/how-can-i-make-a-list-of-exercises-from-a-list-of-triples-to-write-equation-of-t/304597#304597) Can ProfLycee do this? Make some version of exercise from a list of three points

**Comment by cpierquet** [comment]
There's a command to work with cartesian equation of a plan defined by three points... But with 'simples' coefficients, as for resolsysteme ^^

```\documentclass{article}
\usepackage{ProfLycee}

\begin{document}

Une équation cartésienne du plan  passant par le points 
$A\left(\frac{3}{2};-\frac{2}{3};-\frac{4}{5}\right)$ et $B(8;1;5)$, $C(9;3;6)$ est
\[ \TrouveEqCartPlan[SimplifCoeffs,Facteur=-1](3/2,-2/3,-4/5)(8,1,5)(9,3,6) \]

\end{document}```

![image](https://github.com/cpierquet/ProfLycee/assets/45103962/407af6c4-ea10-42eb-8703-858f5b0e8bb4)

**Comment by minhthien2016** [comment]
Thank you very much for your answer. I mean, If I have a list of three points, How can I do this [here](https://mathematica.stackexchange.com/questions/303323/how-can-i-make-some-version-of-exercises-from-a-list-and-get-the-latex-file)?

**Comment by cpierquet** [comment]
Hum ok, maybe with a loop...
But for the moment it's not planned.

**Comment by cpierquet** [comment]
Hum ok, maybe with a loop...
But for the moment it's not planned.
