### ISSUE TITLE
Amélioration de l'affichage des vecteurs dans le texte de la documentation

### ISSUE THREAD

**Issue by quark67** [cpierquet/ProfLycee#9]
Actuellement, les vecteurs s'affichent de manière non optimale dans la documentation. Ainsi, page 123 (section 37.2), nous voyons ceci (j'entoure en rouge ce qui est perfectible) : 
<img width="697" alt="image" src="https://github.com/user-attachments/assets/5f12eed6-7ef8-4991-bb23-332365d00adf">

J'ignore pourquoi il y a le décalage, mais en compilant ce bout de code en LuaLaTeX, la flèche est bien trop petite : 

```latex
\documentclass{article}
\usepackage{fourier-otf}
\begin{document}
$\vec{n}$
\end{document}
```

<img width="53" alt="image" src="https://github.com/user-attachments/assets/0b88a91c-2eec-452d-bfbd-24c6bc541523">

Si on remplace `\usepackage{fourier-otf}` par `\usepackage{fourier}`, toujours en compilant avec LuaLaTeX, on obtient un avertissement : 

```
Package fourier Warning: Please consider loading "fourier-otf.sty" instead of
(fourier)                "fourier.sty" with Unicode engines LuaTeX or XeTeX,
(fourier)                so that Type1 fonts get replaced by OpenType fonts.
```

et ce résultat : 
<img width="54" alt="image" src="https://github.com/user-attachments/assets/7b358af1-d7e2-4f85-82ab-2164a26b5ba2">

En conservant `\usepackage{fourier-otf}`, mais en chargeant le package `esvect`, si l'on remplace `\vec{n}` par `\vv{n}`, on obtient : 
<img width="563" alt="image" src="https://github.com/user-attachments/assets/476d6efb-ec10-4587-823d-86f6325cb6de">

ce qui me semble meilleur. On peut changer le style de flèche en chargeant le package `esvect` avec une option, mais cela provoque une erreur (option clash) lorsque je charge le package `esvect` après tous les autres packages dans le fichier `ProfLycee-doc.tex`. Par contre pas d'erreur de type option clash si je charge le package tout en haut, par exemple avant le chargement de `amsfonts`.

J'ai également tenté l'emploi d'un autre package sensé améliorer l'affichage des flèches de vecteurs (`overarrows`). Je ne suis parvenu à rien de probant lorsque je rajoute ce package dans le préambule du fichier `ProfLycee-doc.tex`. Il y a probablement des conflits.

En effet, avec `\usepackage[overcommands]{overarrows}`, la commande `\overrightarrow` est disponible et avec `\overrightarrow{n}`, j'obtiens : 
<img width="559" alt="image" src="https://github.com/user-attachments/assets/87cb54ae-7d95-450e-a578-48ddf71a64ac">

(la superposition d'un trait horizontal et d'un point d'exclamation. C'est peut-être un problème avec la fonte `fourier-otf`).

Avec la création d'une commande qui utilise Tikz pour le tracé des flèches, j'obtiens encore pire (toujours en conjonction avec le préambule déjà présent dans le fichier `ProfLycee-doc.tex`). Ainsi, avec `\usepackage[overcommands]{overarrows}` et `\NewOverArrowCommand[tikz]{overtikzarrow}{}` (avec une version antérieure à la version 1.2 du package `overarrows`, on ne doit pas mettre `\` devant le nom de la commande crée, tandis qu'à partir de la version 1.2 du package, on peut rajouter le `\` devant le nom de la commande créée, c'est-à-dire `\NewOverArrowCommand[tikz]{\overtikzarrow}{}`), on obtient avec `\overtikzarrow{n}` ceci :
<img width="609" alt="image" src="https://github.com/user-attachments/assets/1e49f02f-ca1b-4ce4-9341-696ec80ba91f">

Peut-être parviendrez-vous à utiliser le package `overarrows` pour votre documentation, sinon le package `esvect` devrait suffire.

**Comment by cpierquet** [comment]
Merci pour le retour, il faut que je vérifie l'impact du chargement des packages liés aux flèches des vecteurs, pour éviter tout incompatibilité.

Pour ce qui est du souci de la page 123, j'ai affiché le vecteur avec la commande `\vec`, pas avec la commande `\Vecteur` :-) 

![image](https://github.com/user-attachments/assets/e6c4fe73-9f5c-4a64-8776-6e0c4356a2d0)

**Comment by quark67** [comment]
Effectivement, l'emploi de la commande `\Vecteur` de votre package en remplacement de la commande `\vec` actuellement employé dans la documentation résoud le problème.

Avec : 

```latex
\begin{PresCodePL}{}
Une équation cartésienne du plan $\mathcal{P}$ de vecteur normal $\Vecteur{n} \AffVecteur(1;2;3)$ et passant par le point A de coordonnées $\AffPoint(4,5,6)$ est $\mathcal{P}$ : $\TrouveEqCartPlan(1;2;3)(4,5,6)$
\end{PresCodePL}
```

on obtient bien un affichage correct : 

<img width="616" alt="image" src="https://github.com/user-attachments/assets/24178d56-4f28-4f11-a9ff-52e88bccccb8">

C'est probablement la meilleure solution 🙂.
